$ANSIBLE_VAULT;1.1;AES256
33356366333836373962613439643664666230313535336335623161326537666439323465343630
6265623433313632303735373661313563373164383134390a633536633830633934633032663431
38333463616161346565636631393034316631313731373734343432626636333033336130323538
3164616264643465360a393435343361663461656130623831386131663833646133623263623239
61326634376633313631373431313664396563663862326362396531396566373434643938346631
61373737346136313333383733333366623732303564633963643630333765623662333035393933
37316466333435616164366530386562653033386164663135323761643966653634346163613137
34356534633764326162626666313763323865313635303630393237666663616361313833393362
6561
